windows linker
src/pmc/bkmarshal.c:299: error: external linkage required for
symbol ‘blizkost_callable_trampoline’ because of ‘dllexport’ attribute